### ISSUE TITLE
Replace Vundler with VimPlug

### ISSUE THREAD

**Issue by aalvarado** [cloverinteractive/dotfiles#69]
I think feature wise Vim Plug is better because it handles async fetching of plugins. 

More info at: https://github.com/junegunn/vim-plug

**Comment by aalvarado** [comment]
Can't assign myself :/

**Comment by EnriqueVidal** [comment]
@aalvarado 

> Can't assign myself :/

Handled

**Comment by EnriqueVidal** [comment]
Solved by #73
